[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/pix/receive"
  to = "/.netlify/functions/pix-receive"
  status = 200

[[redirects]]
  from = "/api/transactions"
  to = "/.netlify/functions/transactions"
  status = 200
